Fix: TypeScript error in `useSSSPTable`
The TypeScript error TS2339: Property 'email' does not exist on type 'SelectQueryError<"could not find the relation between sssp_access and user_id">'.  was resolved.